name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npx eslint .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start services
        run: |
          docker-compose up --build -d

      - name: List running containers
        run: docker-compose ps

      - name: Teardown services
        if: always()
        run: docker-compose down
